In [3]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [2]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [3]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [5]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [6]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
1563/1563 [==============================] - 67s 37ms/step - loss: 1.5168 - accuracy: 0.4449 - val_loss: 1.2591 - val_accuracy: 0.5450
Epoch 2/10
1563/1563 [==============================] - 43s 27ms/step - loss: 1.1730 - accuracy: 0.5836 - val_loss: 1.1113 - val_accuracy: 0.6054
Epoch 3/10
1563/1563 [==============================] - 42s 27ms/step - loss: 1.0188 - accuracy: 0.6424 - val_loss: 1.0124 - val_accuracy: 0.6355
Epoch 4/10
1563/1563 [==============================] - 44s 28ms/step - loss: 0.9139 - accuracy: 0.6787 - val_loss: 0.9542 - val_accuracy: 0.6625
Epoch 5/10
1563/1563 [==============================] - 43s 27ms/step - loss: 0.8430 - accuracy: 0.7049 - val_loss: 0.9147 - val_accuracy: 0.6839
Epoch 6/10
1563/1563 [==============================] - 1497s 958ms/step - loss: 0.7774 - accuracy: 0.7303 - val_loss: 0.8783 - val_accuracy: 0.6935
Epoch 7/10
1563/1563 [==============================] - 42s 27ms/step - loss: 0.7360 - accuracy: 0.7424 - val_loss: 0.883

In [7]:
#Here are some hyperparameters that you can experiment with to improve the performance of the model:
# Change the number of convolutional layers and filters in each layer.
# Increase or decrease the size of the filters.
# Add dropout layers to prevent overfitting.
# Change the number of fully connected layers and neurons in each layer.
# Increase or decrease the learning rate of the optimizer.
# Train the model for more epochs or use early stopping to prevent overfitting.
# Here's an example of how you can train the model for more epochs and add a dropout layer:

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=20, validation_data=(x_test, y_test))



Epoch 1/20
1563/1563 [==============================] - 76s 48ms/step - loss: 1.5941 - accuracy: 0.4115 - val_loss: 1.2875 - val_accuracy: 0.5317
Epoch 2/20
1563/1563 [==============================] - 41s 26ms/step - loss: 1.2914 - accuracy: 0.5349 - val_loss: 1.1674 - val_accuracy: 0.5883
Epoch 3/20
1563/1563 [==============================] - 43s 27ms/step - loss: 1.1615 - accuracy: 0.5874 - val_loss: 1.0143 - val_accuracy: 0.6479
Epoch 4/20
1563/1563 [==============================] - 42s 27ms/step - loss: 1.0860 - accuracy: 0.6125 - val_loss: 1.0182 - val_accuracy: 0.6389
Epoch 5/20
1563/1563 [==============================] - 43s 28ms/step - loss: 1.0126 - accuracy: 0.6406 - val_loss: 0.9583 - val_accuracy: 0.6673
Epoch 6/20
1563/1563 [==============================] - 42s 27ms/step - loss: 0.9622 - accuracy: 0.6587 - val_loss: 0.9046 - val_accuracy: 0.6804
Epoch 7/20
1563/1563 [==============================] - 43s 27ms/step - loss: 0.9298 - accuracy: 0.6703 - val_loss: 0.9136 -

In [8]:
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print('Test accuracy:', test_acc)
from sklearn.metrics import confusion_matrix
import numpy as np

y_pred = np.argmax(model.predict(x_test), axis=-1)
cm = confusion_matrix(np.argmax(y_test, axis=-1), y_pred)

print(cm)


313/313 - 3s - loss: 0.8035 - accuracy: 0.7229 - 3s/epoch - 10ms/step
Test accuracy: 0.7228999733924866
313/313 [==============================] - 3s 9ms/step
[[805  17  29  13  16   1  16   9  81  13]
 [ 27 887   2   1   4   0  15   3  19  42]
 [ 79   8 609  33 109  23  95  26  13   5]
 [ 31   9  93 460 111  77 145  44  16  14]
 [ 22   2  56  20 770   5  83  29  12   1]
 [ 17   4  83 181  91 463  74  73   6   8]
 [ 11   2  31  26  23   5 892   2   7   1]
 [ 24   3  35  32 128  17  11 734   4  12]
 [ 67  35   7  11   7   0   7   3 851  12]
 [ 44 100  10  11   8   0  13   9  47 758]]


In [ ]:
# Here are some techniques you can experiment with to fine-tune the model:

# Data augmentation: Generate additional training data by applying transformations such as rotation, scaling, and flipping to the existing images. This can help the model generalize better to new data and prevent overfitting.

# Dropout: Add dropout layers to the model to randomly drop out some neurons during training, which can prevent overfitting.

# Batch normalization: Normalize the activations of the previous layer at each batch, which can help the model train faster and generalize better.

# Transfer learning: Use a pre-trained model as a starting point and fine-tune it on the CIFAR-10 dataset. This can help the model learn better features and improve its performance.

#This code uses the ImageDataGenerator class from Keras to apply data augmentation to the training set. It also loads a pre-trained VGG16 model and freezes its layers, then adds a few fully connected layers on top of it. Finally, it trains the model on the augmented data for 50 epochs.

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout, BatchNormalization
from tensorflow.keras.applications import VGG16

# Define data augmentation pipeline
train_datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)

train_datagen.fit(x_train)

# Load pre-trained model and fine-tune on CIFAR-10
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(32, 32, 3))
for layer in base_model.layers:
    layer.trainable = False

model = tf.keras.models.Sequential([
    base_model,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    Dropout(0.5),
    BatchNormalization(),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_datagen.flow(x_train, y_train, batch_size=32),
                    epochs=10,
                    validation_data=(x_test, y_test))

